export type Prize = { rank: string; amount: string };

export type Event = {
  id: string;
  title: string;
  category: string;
  venue: string;
  description: string;
  rules: string;
  maxTeamSize: number;
  prizes: Prize[];
  posters: string[];
};

export const events: Event[] = [
  { id: 'circuit-debugging', title: 'Circuit Debugging', category: 'TECHNICAL EVENTS', venue: 'MPMC Lab', description: 'Test your analytical skills and circuit acumen. Locate, identify, and troubleshoot intentional hardware faults and anomalies in electronic and logic circuits.', rules: 'Max 3 members per team. Round 1: Written screening on circuit concepts. Round 2: Hands-on debugging on breadboards with multimeters & components. Speed and proper circuit operation determine the winner.', maxTeamSize: 3, prizes: [{ rank: '1st Prize', amount: '₹2,000' }, { rank: '2nd Prize', amount: '₹1,000' }], posters: ['/static/images/posters/circuit debugging 1.jpeg', '/static/images/posters/circuit debugging 2.jpeg'] },
  { id: 'tech-debate', title: 'Tech Debate', category: 'TECHNICAL EVENTS', venue: 'F101', description: 'A battle of technical wit, rhetoric, and critical reasoning. Debate on emerging technologies, AI impact, and engineering controversies with logical arguments.', rules: '2 members per team. Debate topics provided on the spot with prep time. Structured rounds of opening statements, rebuttals, and jury questions.', maxTeamSize: 2, prizes: [{ rank: '1st Prize', amount: '₹2,000' }, { rank: '2nd Prize', amount: '₹1,000' }], posters: ['/static/images/posters/tech debate 1.jpeg', '/static/images/posters/tech debate 2.jpeg'] },
  { id: 'project-expo', title: 'Project Expo', category: 'TECHNICAL EVENTS', venue: 'Comm Lab', description: 'Showcase your cutting-edge working hardware prototypes, IoT devices, robotics systems, embedded systems, and software engineering projects.', rules: 'Up to 4 members per team. Working model demonstration and project summary required. Judged on innovation, practical feasibility, and presentation clarity.', maxTeamSize: 4, prizes: [{ rank: '1st Prize', amount: '₹2,000' }, { rank: '2nd Prize', amount: '₹1,000' }], posters: ['/static/images/posters/project expo 1.jpeg', '/static/images/posters/project expo 2.jpeg'] },
  { id: 'paper-presentation', title: 'Paper Presentation', category: 'TECHNICAL EVENTS', venue: 'Microwave Lab', description: 'Present original research papers, innovative concepts, and analytical findings in front of an expert panel of academicians.', rules: 'Up to 3 members per team. PPT presentation (8 mins presentation + 2 mins Q&A). Standard IEEE format encouraged.', maxTeamSize: 3, prizes: [{ rank: '1st Prize', amount: '₹2,000' }, { rank: '2nd Prize', amount: '₹1,000' }], posters: ['/static/images/posters/paper presentation.jpeg', '/static/images/posters/paper presentation 2.jpeg'] },
  { id: 'tech-quiz', title: 'Tech Quiz', category: 'TECHNICAL EVENTS', venue: 'DSP Lab', description: 'High-energy multi-round quiz testing your depth in electronics, computing, engineering milestones, science, and global tech trivia.', rules: '2 members per team. Written preliminary screening round followed by live on-stage finals with buzzer and rapid-fire rounds.', maxTeamSize: 2, prizes: [{ rank: '1st Prize', amount: '₹2,000' }, { rank: '2nd Prize', amount: '₹1,000' }], posters: ['/static/images/posters/tech quiz 1.jpeg', '/static/images/posters/tech quiz 2.jpeg', '/static/images/posters/tech quiz 3.jpeg', '/static/images/posters/tech quiz 4.jpeg'] },
  { id: 'men-on-ramp', title: 'Men on Ramp', category: 'NON-TECHNICAL EVENTS', venue: 'APJ Abdul Kalam', description: 'Showcase confidence, personality, attitude, styling, and stage presence in a premier runway fashion contest.', rules: 'Individual participation (1 member). Themed walkthrough, self-introduction, and jury interaction rounds.', maxTeamSize: 1, prizes: [{ rank: '1st Prize', amount: '₹5,000' }, { rank: '2nd Prize', amount: '₹3,000' }], posters: ['/static/images/posters/men on ramp.jpeg'] },
  { id: 'ipl-auction', title: 'IPL Auction', category: 'NON-TECHNICAL EVENTS', venue: 'MPMC Lab', description: 'Strategic cricket squad bidding war. Manage your allocated virtual auction purse to build the ultimate balanced IPL team.', rules: 'Up to 3 members per team. Auction guidelines, player ratings, and purse limits announced at event start.', maxTeamSize: 3, prizes: [{ rank: '1st Prize', amount: '₹1,000' }, { rank: '2nd Prize', amount: '₹500' }], posters: ['/static/images/posters/ipl auction.jpeg'] },
  { id: 'channel-surfing', title: 'Channel Surfing', category: 'NON-TECHNICAL EVENTS', venue: 'ECE Dept, S201', description: 'Spontaneous acting and performance challenge. Switch roles, genres, accents, and emotions instantaneously when the judges switch channels!', rules: 'Up to 5 members per team. Adaptability, humor, and team coordination are prime judging factors.', maxTeamSize: 5, prizes: [{ rank: 'Winner', amount: '₹700' }, { rank: 'Runner', amount: '₹300' }], posters: ['/static/images/posters/chanell surfing.jpeg'] },
  { id: 'connection', title: 'Connection', category: 'NON-TECHNICAL EVENTS', venue: 'ECE Dept, S201', description: 'Visual clue hunt! Connect multiple unrelated images, movie stills, and audio hints to discover hidden tech terms, titles, and words.', rules: '2 members per team. Multi-round visual clue elimination.', maxTeamSize: 2, prizes: [{ rank: 'Winner', amount: '₹700' }, { rank: 'Runner', amount: '₹300' }], posters: ['/static/images/posters/connections.png'] },
  { id: 'e-sports', title: 'E-Sports', category: 'NON-TECHNICAL EVENTS', venue: 'S201 – ECE Dept', description: 'High-intensity mobile gaming tournament featuring Free Fire and FC showdowns.', rules: 'Squad and solo tournament brackets. Standard competition rules enforced.', maxTeamSize: 4, prizes: [{ rank: 'Free Fire - 1st Prize', amount: '₹700' }, { rank: 'Free Fire - 2nd Prize', amount: '₹400' }, { rank: 'FC - 1st Prize', amount: '₹500' }], posters: ['/static/images/posters/e sports.jpeg'] },
  { id: 'console', title: 'Console Clash', category: 'NON-TECHNICAL EVENTS', venue: 'S201 – ECE Dept', description: 'Head-to-head console tournament on controllers with instant knockout arcade matches.', rules: 'Individual 1v1 knockout bracket matches.', maxTeamSize: 1, prizes: [{ rank: '1st Prize', amount: '₹500' }], posters: ['/static/images/posters/console clash.jpeg'] },
  { id: 'decode-the-ams', title: 'Decode the AMS', category: 'NON-TECHNICAL EVENTS', venue: 'E101 – ECE Dept', description: 'Campus-wide cryptic treasure and clue hunt. Crack riddles and logic ciphers to unmask the final destination.', rules: '2 members per team. Timed cipher solving across designated checkpoints.', maxTeamSize: 2, prizes: [{ rank: '1st Prize', amount: '₹700' }, { rank: '2nd Prize', amount: '₹300' }], posters: ['/static/images/posters/decode-the-ams.jpg'] },
  { id: 'stall', title: 'Stalls & Food Exhibits', category: 'STALLS & EXHIBITS', venue: 'Campus Courtyard & Quadrangle', description: 'Commercial, fun, craft, and food stalls setup on campus. Run your own venture during the symposium day!', rules: 'Up to 4 members per stall. Space, standard table, and electrical connection provided. Register your stall venture early!', maxTeamSize: 4, prizes: [{ rank: 'Category', amount: 'Food, Gaming & Commercial Stalls' }], posters: ['/static/images/posters/stall.jpeg'] }
];
